# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:10:37+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class API2ControllersWebAPIGroceryListControllerDepartmentModel(BaseModel):
    items: Optional[str] = Field(None, description='Gets or sets the items.')


class API2ControllersWebAPIGroceryListControllerPostGroceryListAddLineRequest(
    BaseModel
):
    text: Optional[str] = Field(None, description='Gets or sets the text.')


class API2ControllersWebAPIGroceryListControllerPostGroceryListRecipeRequest(BaseModel):
    markAsPending: Optional[bool] = Field(
        None, description='Gets or sets the mark as pending.'
    )
    recipeId: Optional[int] = Field(
        None, description='Gets or sets the recipe identifier.'
    )
    scale: Optional[float] = Field(None, description='Gets or sets the scale.')


class API2ControllersWebAPIGroceryListControllerPostToGroceryListRecipeRequest(
    BaseModel
):
    department: Optional[str] = Field(None, description='Gets or sets the department.')
    name: Optional[str] = Field(None, description='Gets or sets the name.')
    notes: Optional[str] = Field(None, description='Gets or sets the notes.')
    quantity: Optional[str] = Field(None, description='Gets or sets the quantity.')
    unit: Optional[str] = Field(None, description='Gets or sets the unit.')


class API2ControllersWebAPIGroceryListControllerUpdateItemByGuidRequest(BaseModel):
    department: Optional[str] = Field(None, description='Gets or sets the department.')
    guid: Optional[str] = Field(None, description='Gets or sets the unique identifier.')
    ischecked: Optional[bool] = Field(None, description='Gets or sets the ischecked.')
    name: Optional[str] = Field(None, description='Gets or sets the name.')
    notes: Optional[str] = Field(None, description='Gets or sets the notes.')
    quantity: Optional[str] = Field(None, description='Gets or sets the quantity.')
    unit: Optional[str] = Field(None, description='Gets or sets the unit.')


class API2ControllersWebAPIMeControllerOption(BaseModel):
    Description: Optional[str] = Field(
        None, description='Gets or sets the description.'
    )
    Key: Optional[str] = Field(None, description='Gets or sets the key.')


class API2ControllersWebAPINoteControllerNoteRequest(BaseModel):
    CreationDate: Optional[datetime] = Field(
        None, description='Gets or sets the creation date.'
    )
    Date: Optional[datetime] = Field(None, description='Gets or sets the date.')
    DateDT: Optional[str] = Field(None, description='Gets or sets the date dt.')
    GUID: Optional[str] = Field(None, description='Gets or sets the unique identifier.')
    ID: Optional[int] = Field(None, description='Gets or sets the identifier.')
    Notes: Optional[str] = Field(None, description='Gets or sets the notes.')
    People: Optional[str] = Field(None, description='Gets or sets the people.')
    RecipeID: Optional[int] = Field(
        None, description='Gets or sets the recipe identifier.'
    )
    UserID: Optional[int] = Field(None, description='Gets or sets the user identifier.')
    Variations: Optional[str] = Field(None, description='Gets or sets the variations.')


class API2ControllersWebAPIReviewControllerPostReplyReq(BaseModel):
    Comment: Optional[str] = Field(
        None,
        description='The comment. If mentioning any user(s) (optional), include them as @username in the text body. Do not use @ symbol for anything but mentioning @usernames.',
    )


class API2ControllersWebAPIReviewControllerReviewRequest(BaseModel):
    ActiveMinutes: Optional[int] = Field(
        None,
        description='How many minutes of ACTIVE time (i.e., actively working on the recipe, not waiting for rising, baking, etc.) did it \r\n            demand of the cook? Optional.',
    )
    Comment: Optional[str] = Field(None, description='The notes')
    MakeAgain: Optional[str] = Field(None, description='"yes" or "no"')
    StarRating: Optional[int] = Field(None, description='1, 2, 3, 4, or 5')
    TotalMinutes: Optional[int] = Field(
        None,
        description='How long, start to finish, in minutes (integer) did it take? Optional.',
    )


class API2ControllersWebAPIReviewControllerReviewRequestLegacy(BaseModel):
    ActiveMinutes: Optional[int] = None
    Comment: Optional[str] = None
    GUID: Optional[str] = None
    MakeAgain: Optional[str] = None
    ParentID: Optional[int] = None
    StarRating: Optional[int] = None
    TotalMinutes: Optional[int] = None


class API2GroceryListDepartmentResult(BaseModel):
    dept: Optional[str] = Field(None, description='Gets or sets the dept.')
    item: Optional[str] = Field(None, description='Gets or sets the item.')


class API2ModelsAccounting(BaseModel):
    CreditBalance: Optional[int] = Field(None, description='')
    MemberSince: Optional[datetime] = Field(None, description='')
    PremiumExpiryDate: Optional[datetime] = Field(None, description='')
    UserLevel: Optional[str] = Field(None, description='')


class API2ModelsCounts(BaseModel):
    AddedCount: Optional[int] = Field(None, description='')
    FollowersCount: Optional[int] = Field(None, description='')
    FollowingCount: Optional[int] = Field(None, description='')
    PrivateRecipeCount: Optional[int] = Field(None, description='')
    PublicRecipeCount: Optional[int] = Field(None, description='')
    TotalRecipes: Optional[int] = Field(None, description='')


class API2ModelsLocation(BaseModel):
    City: Optional[str] = Field(None, description='')
    Country: Optional[str] = Field(None, description='')
    DMA: Optional[int] = Field(None, description='')


class API2ModelsPersonal(BaseModel):
    Email: Optional[str] = Field(None, description='')
    Location: Optional[API2ModelsLocation] = None


class API2ModelsPreference(BaseModel):
    EatingStyle: Optional[str] = Field(None, description='')


class API2ModelsProfile(BaseModel):
    AboutMe: Optional[str] = Field(None, description='')
    BackgroundUrl: Optional[str] = Field(None, description='')
    Counts: Optional[API2ModelsCounts] = None
    FirstName: Optional[str] = Field(None, description='')
    FullName: Optional[str] = Field(None, description='')
    HomeUrl: Optional[str] = Field(None, description='')
    LastName: Optional[str] = Field(None, description='')
    PhotoUrl: Optional[str] = Field(None, description='')
    UserID: Optional[int] = Field(None, description='')
    UserName: Optional[str] = Field(None, description='')


class API2ModelsRecipesFeedbackDTO(BaseModel):
    feedback: Optional[str] = None


class API2ModelsRecipesRecipeVideoResponse(BaseModel):
    InsertedOn: Optional[datetime] = Field(
        None, description='Gets or sets the date the video was added.'
    )
    IsPrimaryVideo: Optional[bool] = Field(
        None,
        description='Gets or sets a value indicating whether the video is the primary video of the recipe.',
    )
    MediaId: Optional[str] = Field(
        None, description='Gets or sets the JWPlayer media id.'
    )
    VidId: Optional[int] = Field(None, description='Gets or sets the video id.')


class BigOvenModelAPIGroceryItem(BaseModel):
    BigOvenObject: Optional[str] = None
    CreationDate: Optional[datetime] = None
    Department: Optional[str] = None
    DisplayQuantity: Optional[str] = None
    GUID: Optional[str] = None
    IsChecked: Optional[bool] = None
    ItemID: Optional[int] = None
    LastModified: Optional[datetime] = None
    LocalStatus: Optional[str] = None
    Name: Optional[str] = None
    Notes: Optional[str] = None
    RecipeID: Optional[int] = None
    ThirdPartyURL: Optional[str] = None


class BigOvenModelAPIIngredientInfo(BaseModel):
    Department: Optional[str] = None
    MasterIngredientID: Optional[int] = None
    Name: Optional[str] = None
    UsuallyOnHand: Optional[bool] = None


class BigOvenModelAPINutritionInfo(BaseModel):
    CaloriesFromFat: Optional[float] = None
    Cholesterol: Optional[float] = None
    CholesterolPct: Optional[float] = None
    DietaryFiber: Optional[float] = None
    DietaryFiberPct: Optional[float] = None
    MonoFat: Optional[float] = None
    PolyFat: Optional[float] = None
    Potassium: Optional[float] = None
    PotassiumPct: Optional[float] = None
    Protein: Optional[float] = None
    ProteinPct: Optional[float] = None
    SatFat: Optional[float] = None
    SatFatPct: Optional[float] = None
    SingularYieldUnit: Optional[str] = None
    Sodium: Optional[float] = None
    SodiumPct: Optional[float] = None
    Sugar: Optional[float] = None
    TotalCalories: Optional[float] = None
    TotalCarbs: Optional[float] = None
    TotalCarbsPct: Optional[float] = None
    TotalFat: Optional[float] = None
    TotalFatPct: Optional[float] = None
    TransFat: Optional[float] = None


class BigOvenModelAPIRecipeNote(BaseModel):
    CreationDate: Optional[datetime] = None
    Date: Optional[str] = None
    DateDT: Optional[datetime] = None
    GUID: Optional[str] = None
    ID: Optional[int] = None
    Notes: Optional[str] = None
    People: Optional[str] = None
    RecipeID: Optional[int] = None
    UserID: Optional[int] = None
    Variations: Optional[str] = None


class BigOvenModelAPIRecipeNoteList(BaseModel):
    ResultCount: Optional[int] = None
    Results: Optional[List[BigOvenModelAPIRecipeNote]] = None


class BigOvenModelAPIUserInfo(BaseModel):
    FirstName: Optional[str] = None
    ImageUrl48: Optional[str] = None
    IsKitchenHelper: Optional[bool] = None
    IsPremium: Optional[bool] = None
    IsUsingRecurly: Optional[bool] = None
    LastName: Optional[str] = None
    MemberSince: Optional[datetime] = None
    PhotoUrl: Optional[str] = None
    PhotoUrl48: Optional[str] = None
    PremiumExpiryDate: Optional[datetime] = None
    UserID: Optional[int] = None
    UserName: Optional[str] = None
    WebUrl: Optional[str] = None


class BigOvenModelAPIUserInfoTiny(BaseModel):
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    PhotoUrl: Optional[str] = None
    UserID: Optional[int] = None
    UserName: Optional[str] = None


class BigOvenModelAPI2RecipeNote(BaseModel):
    CreationDate: Optional[datetime] = None
    Date: Optional[str] = None
    DateDT: Optional[datetime] = None
    GUID: Optional[str] = None
    ID: Optional[int] = None
    Notes: Optional[str] = None
    People: Optional[str] = None
    RecipeID: Optional[int] = None
    UserID: Optional[int] = None
    Variations: Optional[str] = None


class BigOvenModelAPI2UserInfoTinyx(BaseModel):
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    PhotoUrl: Optional[str] = None
    UserID: Optional[int] = None
    UserName: Optional[str] = None


class BigOvenModelInstructionStep(BaseModel):
    EndGantt: Optional[int] = None
    StartGantt: Optional[int] = None
    Text: Optional[str] = None


class BigOvenModelRecipeCategory(BaseModel):
    Category: Optional[str] = None
    DefaultActiveMinutes: Optional[int] = None
    DefaultTotalMinutes: Optional[int] = None
    ID: Optional[int] = None
    ParentID: Optional[int] = None
    PrimaryImage: Optional[str] = None
    ShortDescription: Optional[str] = None


class BigOvenModelRecipeInfoTiny(BaseModel):
    ImageURL: Optional[str] = None
    QualityScore: Optional[int] = None
    RecipeID: Optional[int] = None
    Servings: Optional[float] = None
    Title: Optional[str] = None


class BigOvenModelShoppingListLine(BaseModel):
    DateAdded: Optional[datetime] = None
    Dept: Optional[str] = None
    GUID: Optional[str] = None
    HTMLItemName: Optional[str] = None
    IsChecked: Optional[bool] = None
    ItemName: Optional[str] = None
    LastModified: Optional[datetime] = None
    ListID: Optional[int] = None
    MealPlanID: Optional[int] = None
    MealPlanObjectType: Optional[int] = None
    Notes: Optional[str] = None
    PendingAddition: Optional[bool] = None
    RecipeID: Optional[int] = None
    ShoppingListLineID: Optional[int] = None
    Store: Optional[str] = None
    TextAmt: Optional[str] = None
    ThirdPartyHost: Optional[str] = None
    ThirdPartyTitle: Optional[str] = None
    ThirdPartyURL: Optional[str] = None


class SystemObject(BaseModel):
    pass


class GrocerylistDepartmentPostResponse(
    RootModel[List[API2GroceryListDepartmentResult]]
):
    root: List[API2GroceryListDepartmentResult]


class RecipeAutocompleteGetResponse(RootModel[List[str]]):
    root: List[str]


class RecipeAutocompleteAllGetResponse(RootModel[List[BigOvenModelRecipeInfoTiny]]):
    root: List[BigOvenModelRecipeInfoTiny]


class RecipeAutocompleteMineGetResponse(RootModel[List[BigOvenModelRecipeInfoTiny]]):
    root: List[BigOvenModelRecipeInfoTiny]


class RecipeCategoriesGetResponse(RootModel[List[BigOvenModelRecipeCategory]]):
    root: List[BigOvenModelRecipeCategory]


class API2ControllersWebAPIMeControllerEatingStyle(BaseModel):
    Options: Optional[List[API2ControllersWebAPIMeControllerOption]] = Field(
        None, description='Gets or sets the options.'
    )


class API2ControllersWebAPIMeControllerPreferenceOptions(BaseModel):
    EatingStyle: Optional[API2ControllersWebAPIMeControllerEatingStyle] = None


class API2ModelsBigOvenUser(BaseModel):
    Accounting: Optional[API2ModelsAccounting] = None
    BOAuthToken: Optional[str] = Field(
        None, description='The user-specific authentication token'
    )
    LastChangeLogID: Optional[str] = Field(None, description='Last change log')
    Personal: Optional[API2ModelsPersonal] = None
    Preferences: Optional[API2ModelsPreference] = None
    Profile: Optional[API2ModelsProfile] = None


class API2Result(BaseModel):
    Data: Optional[SystemObject] = None
    Message: Optional[str] = None
    StatusCode: Optional[int] = None


class BigOvenModelAPIImage(BaseModel):
    Caption: Optional[str] = None
    CreationDate: Optional[str] = None
    ImageID: Optional[int] = None
    ImageSquares: Optional[List[int]] = None
    ImageURL: Optional[str] = None
    ImageURL120: Optional[str] = None
    ImageURL128: Optional[str] = None
    ImageURL200: Optional[str] = None
    ImageURL256: Optional[str] = None
    ImageURL48: Optional[str] = None
    ImageURL64: Optional[str] = None
    IsPrimary: Optional[bool] = None
    MaxImageSquare: Optional[int] = None
    Poster: Optional[BigOvenModelAPIUserInfo] = None


class BigOvenModelAPIIngredient(BaseModel):
    DisplayIndex: Optional[int] = None
    DisplayQuantity: Optional[str] = None
    HTMLName: Optional[str] = None
    IngredientID: Optional[int] = None
    IngredientInfo: Optional[BigOvenModelAPIIngredientInfo] = None
    IsHeading: Optional[bool] = None
    IsLinked: Optional[bool] = None
    MetricDisplayQuantity: Optional[str] = None
    MetricQuantity: Optional[float] = None
    MetricUnit: Optional[str] = None
    Name: Optional[str] = None
    PreparationNotes: Optional[str] = None
    Quantity: Optional[float] = None
    Unit: Optional[str] = None


class BigOvenModelAPIRecipe(BaseModel):
    ActiveMinutes: Optional[int] = None
    AdTags: Optional[str] = None
    AdminBoost: Optional[int] = None
    AllCategoriesText: Optional[str] = None
    BookmarkImageURL: Optional[str] = None
    BookmarkSiteLogo: Optional[str] = None
    BookmarkURL: Optional[str] = None
    Category: Optional[str] = None
    Collection: Optional[str] = None
    CollectionID: Optional[int] = None
    CreationDate: Optional[datetime] = None
    Cuisine: Optional[str] = None
    Description: Optional[str] = None
    FavoriteCount: Optional[int] = None
    HeroPhotoUrl: Optional[str] = None
    ImageSquares: Optional[List[int]] = None
    ImageURL: Optional[str] = None
    Ingredients: Optional[List[BigOvenModelAPIIngredient]] = None
    IngredientsTextBlock: Optional[str] = None
    Instructions: Optional[str] = None
    IsBookmark: Optional[bool] = None
    IsPrivate: Optional[bool] = None
    IsRecipeScan: Optional[bool] = None
    IsSponsored: Optional[bool] = None
    LastModified: Optional[datetime] = None
    MaxImageSquare: Optional[int] = None
    MedalCount: Optional[int] = None
    MenuCount: Optional[int] = None
    Microcategory: Optional[str] = None
    NotesCount: Optional[int] = None
    NutritionInfo: Optional[BigOvenModelAPINutritionInfo] = None
    Poster: Optional[BigOvenModelAPIUserInfo] = None
    PrimaryIngredient: Optional[str] = None
    RecipeID: Optional[int] = None
    ReviewCount: Optional[int] = None
    StarRating: Optional[float] = None
    Subcategory: Optional[str] = None
    Title: Optional[str] = None
    TotalMinutes: Optional[int] = None
    VariantOfRecipeID: Optional[int] = None
    VerifiedByClass: Optional[str] = None
    VerifiedDateTime: Optional[datetime] = None
    WebURL: Optional[str] = None
    YieldNumber: Optional[float] = None
    YieldUnit: Optional[str] = None


class BigOvenModelAPIRecipeInfo(BaseModel):
    BookmarkURL: Optional[str] = None
    Category: Optional[str] = None
    CreationDate: Optional[datetime] = None
    Cuisine: Optional[str] = None
    HasVideos: Optional[bool] = None
    HeroPhotoUrl: Optional[str] = None
    HideFromPublicSearch: Optional[bool] = None
    ImageURL: Optional[str] = None
    ImageURL120: Optional[str] = None
    IsBookmark: Optional[bool] = None
    IsPrivate: Optional[bool] = None
    MaxImageSquare: Optional[int] = None
    Microcategory: Optional[str] = None
    Poster: Optional[BigOvenModelAPIUserInfo] = None
    QualityScore: Optional[float] = None
    RecipeID: Optional[int] = None
    ReviewCount: Optional[int] = None
    StarRating: Optional[float] = None
    StarRatingIMG: Optional[str] = None
    Subcategory: Optional[str] = None
    Title: Optional[str] = None
    TotalTries: Optional[int] = None
    WebURL: Optional[str] = None
    YieldNumber: Optional[float] = None


class BigOvenModelAPIReply(BaseModel):
    Comment: Optional[str] = None
    CreationDate: Optional[datetime] = None
    ID: Optional[str] = None
    LastModified: Optional[datetime] = None
    Poster: Optional[BigOvenModelAPIUserInfoTiny] = None
    ReviewID: Optional[str] = None


class BigOvenModelAPIReview(BaseModel):
    ActiveMinutes: Optional[int] = None
    Comment: Optional[str] = None
    CreationDate: Optional[datetime] = None
    FeaturedReply: Optional[BigOvenModelAPIReply] = None
    GUID: Optional[str] = None
    ID: Optional[str] = None
    LastModified: Optional[datetime] = None
    ParentID: Optional[int] = None
    Poster: Optional[BigOvenModelAPIUserInfo] = None
    Replies: Optional[List[BigOvenModelAPIReview]] = None
    ReplyCount: Optional[int] = None
    ReviewID: Optional[int] = None
    StarRating: Optional[float] = None
    TotalMinutes: Optional[int] = None


class BigOvenModelAPI2Photo(BaseModel):
    Caption: Optional[str] = None
    CreationDate: Optional[str] = None
    ImageID: Optional[int] = None
    IsPrimary: Optional[bool] = None
    MaxImageSquare: Optional[int] = None
    PhotoUrl: Optional[str] = None
    Poster: Optional[BigOvenModelAPI2UserInfoTinyx] = None


class BigOvenModelAPI2Recipe(BaseModel):
    ActiveMinutes: Optional[int] = None
    AdTags: Optional[str] = None
    AdminBoost: Optional[int] = None
    AllCategoriesText: Optional[str] = None
    BookmarkImageURL: Optional[str] = None
    BookmarkSiteLogo: Optional[str] = None
    BookmarkURL: Optional[str] = None
    Category: Optional[str] = None
    Collection: Optional[str] = None
    CollectionID: Optional[int] = None
    CreationDate: Optional[datetime] = None
    Cuisine: Optional[str] = None
    Description: Optional[str] = None
    FavoriteCount: Optional[int] = None
    ImageSquares: Optional[List[int]] = None
    ImageURL: Optional[str] = None
    Ingredients: Optional[List[BigOvenModelAPIIngredient]] = None
    IngredientsTextBlock: Optional[str] = None
    Instructions: Optional[str] = None
    IsBookmark: Optional[bool] = None
    IsPrivate: Optional[bool] = None
    IsRecipeScan: Optional[bool] = None
    IsSponsored: Optional[bool] = None
    LastModified: Optional[datetime] = None
    MaxImageSquare: Optional[int] = None
    MedalCount: Optional[int] = None
    MenuCount: Optional[int] = None
    Microcategory: Optional[str] = None
    NotesCount: Optional[int] = None
    NutritionInfo: Optional[BigOvenModelAPINutritionInfo] = None
    PhotoUrl: Optional[str] = None
    Poster: Optional[BigOvenModelAPIUserInfo] = None
    PrimaryIngredient: Optional[str] = None
    RecipeID: Optional[int] = None
    ReviewCount: Optional[int] = None
    StarRating: Optional[float] = None
    Steps: Optional[List[BigOvenModelInstructionStep]] = None
    Subcategory: Optional[str] = None
    Title: Optional[str] = None
    TotalMinutes: Optional[int] = None
    VariantOfRecipeID: Optional[int] = None
    VerifiedByClass: Optional[str] = None
    VerifiedDateTime: Optional[datetime] = None
    WebURL: Optional[str] = None
    YieldNumber: Optional[float] = None
    YieldUnit: Optional[str] = None


class BigOvenModelAPI2RecipeInfox(BaseModel):
    Category: Optional[str] = None
    CreationDate: Optional[datetime] = None
    Cuisine: Optional[str] = None
    HasVideos: Optional[bool] = None
    IsBookmark: Optional[bool] = None
    IsPrivate: Optional[bool] = None
    IsRecipeScan: Optional[bool] = None
    Microcategory: Optional[str] = None
    PhotoUrl: Optional[str] = None
    Poster: Optional[BigOvenModelAPI2UserInfoTinyx] = None
    RecipeID: Optional[int] = None
    ReviewCount: Optional[int] = None
    Servings: Optional[float] = None
    StarRating: Optional[float] = None
    Subcategory: Optional[str] = None
    Title: Optional[str] = None
    TotalTries: Optional[int] = None
    WebURL: Optional[str] = None


class BigOvenModelAPI2RecipeSearchResult(BaseModel):
    ResultCount: Optional[int] = None
    Results: Optional[List[BigOvenModelAPI2RecipeInfox]] = None
    SpellSuggest: Optional[str] = None


class BigOvenModelRecipeInfoDateTuple2(BaseModel):
    date: Optional[datetime] = None
    recipeInfo: Optional[BigOvenModelAPI2RecipeInfox] = None


class BigOvenModelRecipeInfoReviewTuple2(BaseModel):
    RecipeInfo: Optional[BigOvenModelAPI2RecipeInfox] = None
    Review: Optional[BigOvenModelAPIReview] = None


class BigOvenResult(BaseModel):
    Data: Optional[SystemObject] = None
    Message: Optional[str] = None
    StatusCode: Optional[int] = None


class RecipeReviewReviewIdRepliesGetResponse(RootModel[List[BigOvenModelAPIReply]]):
    root: List[BigOvenModelAPIReply]


class RecipeRecipeIdImagesGetResponse(RootModel[List[BigOvenModelAPIImage]]):
    root: List[BigOvenModelAPIImage]


class RecipeRecipeIdReviewsGetResponse(RootModel[List[BigOvenModelAPIReview]]):
    root: List[BigOvenModelAPIReview]


class RecipeRecipeIdScansGetResponse(RootModel[List[BigOvenModelAPIImage]]):
    root: List[BigOvenModelAPIImage]


class RecipesRavesGetResponse(RootModel[List[BigOvenModelRecipeInfoReviewTuple2]]):
    root: List[BigOvenModelRecipeInfoReviewTuple2]


class RecipesRecentviewsGetResponse(RootModel[List[BigOvenModelRecipeInfoDateTuple2]]):
    root: List[BigOvenModelRecipeInfoDateTuple2]


class API2ControllersWebAPIImagesControllerRecipePhotosResponse(BaseModel):
    ResultCount: Optional[int] = Field(
        None, description='Gets or sets the result count.'
    )
    Results: Optional[List[BigOvenModelAPI2Photo]] = Field(
        None, description='Gets or sets the results.'
    )


class API2ModelsRecipesRecipeResponse(BaseModel):
    ActiveMinutes: Optional[int] = None
    AdTags: Optional[str] = None
    AdminBoost: Optional[int] = None
    AllCategoriesText: Optional[str] = None
    BookmarkImageURL: Optional[str] = None
    BookmarkSiteLogo: Optional[str] = None
    BookmarkURL: Optional[str] = None
    Category: Optional[str] = None
    Collection: Optional[str] = None
    CollectionID: Optional[int] = None
    CreationDate: Optional[datetime] = None
    Cuisine: Optional[str] = None
    Description: Optional[str] = None
    FavoriteCount: Optional[int] = None
    ImageSquares: Optional[List[int]] = None
    ImageURL: Optional[str] = None
    Ingredients: Optional[List[BigOvenModelAPIIngredient]] = None
    IngredientsTextBlock: Optional[str] = None
    Instructions: Optional[str] = None
    IsBookmark: Optional[bool] = None
    IsPrivate: Optional[bool] = None
    IsRecipeScan: Optional[bool] = None
    IsSponsored: Optional[bool] = None
    LastModified: Optional[datetime] = None
    MaxImageSquare: Optional[int] = None
    MedalCount: Optional[int] = None
    MenuCount: Optional[int] = None
    Microcategory: Optional[str] = None
    NotesCount: Optional[int] = None
    NutritionInfo: Optional[BigOvenModelAPINutritionInfo] = None
    PhotoUrl: Optional[str] = None
    Poster: Optional[BigOvenModelAPIUserInfo] = None
    PrimaryIngredient: Optional[str] = None
    RecipeID: Optional[int] = None
    ReviewCount: Optional[int] = None
    StarRating: Optional[float] = None
    Steps: Optional[List[BigOvenModelInstructionStep]] = None
    Subcategory: Optional[str] = None
    Title: Optional[str] = None
    TotalMinutes: Optional[int] = None
    VariantOfRecipeID: Optional[int] = None
    VerifiedByClass: Optional[str] = None
    VerifiedDateTime: Optional[datetime] = None
    Videos: Optional[List[API2ModelsRecipesRecipeVideoResponse]] = Field(
        None,
        description='Gets or sets the recipe videos, i.e. a list of type {API2_Models_Recipes_RecipeVideoResponse}',
    )
    WebURL: Optional[str] = None
    YieldNumber: Optional[float] = None
    YieldUnit: Optional[str] = None


class BigOvenModelAPIGroceryGroceryList(BaseModel):
    Items: Optional[List[BigOvenModelAPIGroceryItem]] = None
    LastModified: Optional[datetime] = None
    Recipes: Optional[List[BigOvenModelAPIRecipeInfo]] = None
    VersionGuid: Optional[str] = None


class BigOvenModelAPI2CollectionInfo(BaseModel):
    Description: Optional[str] = None
    ID: Optional[int] = None
    IsFiltered: Optional[bool] = None
    IsSponsored: Optional[bool] = None
    MobileUrl: Optional[str] = None
    PRO: Optional[bool] = None
    PhotoUrl: Optional[str] = None
    Results: Optional[List[BigOvenModelAPI2RecipeInfox]] = None
    Title: Optional[str] = None
    Token: Optional[str] = None
    WebUrl: Optional[str] = None


class BigOvenModelAPI2GroceryList(BaseModel):
    Items: Optional[List[BigOvenModelAPIGroceryItem]] = None
    LastModified: Optional[datetime] = None
    Recipes: Optional[List[BigOvenModelAPI2RecipeInfox]] = None
    VersionGuid: Optional[str] = None


class CollectionsGetResponse(RootModel[List[BigOvenModelAPI2CollectionInfo]]):
    root: List[BigOvenModelAPI2CollectionInfo]


class API2ControllersWebAPIGroceryListControllerPostGroceryListSyncRequest(BaseModel):
    list: Optional[BigOvenModelAPIGroceryGroceryList] = None
    since: Optional[str] = Field(None, description='Gets or sets the since.')


BigOvenModelAPIReview.model_rebuild()
